---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: edge-demo
  namespace: edgy
spec:
  chart:
    spec:
      chart: edge-demo
      sourceRef:
        kind: HelmRepository
        name: edge-demo
        namespace: edgy 
      version: 0.1.0
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  releaseName: edge-demo
  targetNamespace: edgy

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: edge-demo
  namespace: edgy
spec:
  interval: 10m
  timeout: 1m
  url: https://raw.githubusercontent.com/arbhoj/edge-demo/main/edge-demo-charts
