---
apiVersion: v1
kind: ConfigMap
data:
  index.html: |
    <html>
        <head>
            <title>{{ include "dynamic.clusterName" . }} Online!!</title>
        </head>
            <body>
                <h1>{{ include "dynamic.clusterName" . }} Online!!</h1>
                <img src="https://raw.githubusercontent.com/arbhoj/edge-demo/refs/heads/main/images/welcome_to_edge_medium.gif">
            </body>
    </html>
metadata:
  name: globalmainpage
  namespace: {{ .Release.Namespace }}
