apiVersion: v1
kind: ConfigMap
metadata:
  name: globalmainpage
  namespace: {{ .Release.Namespace }}
data:
  index.html: |
    <html>
        <head>
            <title>{{ include "dynamic.clusterName" . }} Online!!</title>      
        </head>
            <body>
                <h1>{{ include "dynamic.clusterName" . }} Online!!</h1>
                <div class="imgbox">
                    <img src="https://raw.githubusercontent.com/arbhoj/edge-demo/refs/heads/main/images/welcome_to_edge_medium.gif">
                </div>
            </body>
    </html>