apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloedge
  name: helloedge
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: helloedge
